/*
 * PwdToolMain.java
 *
 * Created on __DATE__, __TIME__
 */

package com.yzj.wf.ebs.security.tool.app;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.SimpleDateFormat;
import java.util.Date;

import com.yzj.wf.ebs.security.tool.SecurityTool;

/**
 *
 * @author  __USER__
 */
public class PwdToolMain extends javax.swing.JFrame {

	/** Creates new form PwdToolMain */
	public PwdToolMain() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jfc = new javax.swing.JFileChooser();
		dataDatetxt = new javax.swing.JTextField();
		datadatelable = new javax.swing.JLabel();
		passwordlable = new javax.swing.JLabel();
		passwordTxt = new javax.swing.JPasswordField();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		datadatelable.setText("\u6587\u4ef6\u8def\u5f84");

		passwordlable.setText("\u5bc6\u7801\uff1a");
		jfc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				File f=jfc.getSelectedFile();//f为选择到的文件
				dataDatetxt.setText(f.getAbsolutePath());  
			}
		});
		passwordTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				passwordTxtActionPerformed(evt);
			}
		});

		jButton1.setText("\u70b9\u51fb\u89e3\u5bc6");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jfc,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														663,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jButton1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						185,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														datadatelable,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														65,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														passwordlable,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														52,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														passwordTxt,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														177,
																														javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(
																														dataDatetxt,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														567,
																														javax.swing.GroupLayout.PREFERRED_SIZE))))))
								.addContainerGap(232, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jfc,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										287,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														datadatelable,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														25,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														dataDatetxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														passwordlable,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														21,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														passwordTxt,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														25,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton1)
								.addContainerGap(109, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
		boolean isAllow = true;
		if (dataDatetxt.getText() == null || "".equals(dataDatetxt.getText())) {
			// 提示请输入日期
			javax.swing.JOptionPane
					.showMessageDialog(dataDatetxt, "请选择解密文件路径！");
		} else if (passwordTxt.getText() == null
				|| "".equals(passwordTxt.getText())) {
			// 提示请输入日期
			javax.swing.JOptionPane.showMessageDialog(passwordTxt, "请输入密码！");
		} else {
			String filePath = dataDatetxt.getText(); //需要解密的文件路径
			String pwd = passwordTxt.getText(); //解密时输入的解密密码
			// 生成解密后的文件
			//String path = filePath.substring(0,filePath.lastIndexOf("\\")+1) + getNowDate() + "_EbillData_XE.txt"; //解密后生成的文件
			String path = filePath.split("\\.")[0] + "_XE.txt"; //解密后生成的文件
			try {
				SecurityTool st = new SecurityTool(SecurityTool.base64);
				File file = new File(filePath);
				BufferedReader reader = null;
				String tempString = null;
				reader = new BufferedReader(new InputStreamReader(
						new FileInputStream(file), "utf-8"));
				int i = 0; //标识 i=0 是 第一行的密码 
				//String strLineValue=null; 	//存放解密后的行值
				StringBuffer all_str = new StringBuffer();
				// 一次读入一行，直到读入null为文件结束
				while ((tempString = reader.readLine()) != null) {
					i++;
					if (i == 1) {
						String p = st.decrypt(tempString);
						if (!pwd.equals(p)) {
							// 提示请输入日期
							javax.swing.JOptionPane.showMessageDialog(
									passwordTxt, "密码错！");
							isAllow = false;
							break;
						}
					} else {
						//在eclipse里运行编码正常
						//strLineValue=new String(st.decrypt(tempString).getBytes("utf-8"),"utf-8");
						//					strLineValue=new String(st.decrypt(tempString).getBytes("GBK"),"utf-8");
						//					writeTxtFile(path, strLineValue);
						all_str.append(tempString);
					}
				}
				if (isAllow) {
					writeTxtFile(path, new String(st
							.decrypt(all_str.toString()).getBytes("utf-8"),
							"utf-8"));
					javax.swing.JOptionPane.showMessageDialog(jfc, "解密成功！");
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
	}

	private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PwdToolMain().setVisible(true);
			}
		});
	}
	/**
	 * 当前日期
	 * @return
	 */
	public String getNowDate() {
		Date newdate = new Date();
		SimpleDateFormat sf = new SimpleDateFormat("yyyyMMdd");
		String dateformat = sf.format(newdate);
		return dateformat;
	}

	/**
	 * 解密后生成明文的文本文件
	 * @param filepath 生成文件路径
	 * @param str 解密后的每行数据
	 */
	public void writeTxtFile(String filepath, String str) {
		FileWriter filewriter = null;
		try {
			File file = new File(filepath);
			if (file.exists()) {
				file.delete();
				filewriter = new FileWriter(file, true);
			} else {
				if (file.createNewFile()) {
					filewriter = new FileWriter(file, true);
				} else {
					javax.swing.JOptionPane.showMessageDialog(jfc, "创建文件失败！");
				}
			}
			if (filewriter != null) {
				try {
					filewriter.write(str);
					filewriter.flush();
				} catch (IOException e) {
					javax.swing.JOptionPane.showMessageDialog(jfc, "创建文件失败！");
					e.printStackTrace();
				}finally{
					filewriter.close();
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JTextField dataDatetxt;
	private javax.swing.JLabel datadatelable;
	private javax.swing.JButton jButton1;
	private javax.swing.JFileChooser jfc;
	private javax.swing.JPasswordField passwordTxt;
	private javax.swing.JLabel passwordlable;
	// End of variables declaration//GEN-END:variables

}